<html>
    <head>
        <meta charset="UTf-8">
        <title>Distribuidora</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="/css/estilo.css">
    </head>
    <body>  
        <div id ="fondo_inicio" align="center">
            <div id="fondo_text">Distribuidora</div>
        </div>
        
